#CREAMOS UNA BASE DE DATOS 
CREATE DATABASE DB_FACTURACION;

#INDICAMOS AL SERVIDOR LA BASE DATOS A USAR
USE dbfacturacion;

#CREAR LA TABLA USUARIO
CREATE TABLE USUARIO
(CODIGO INT PRIMARY KEY,
ROL VARCHAR(50) NOT NULL,
CLAVE VARCHAR(50),
USUARIO VARCHAR(50),
EMAIL VARCHAR(320));


#CREAR TABLA EMPLEADO
CREATE TABLE TBLEMPLEADO
(nocedula BIGINT PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
telefono VARCHAR(7),
celular VARCHAR(10),
fechanacimiento VARCHAR(10), 
genero VARCHAR(30),  
tipodoc VARCHAR(50),
direccion VARCHAR(100));


select * from tblempleado;




