#CREAMOS UNA BASE DE DATOS 
CREATE DATABASE DB_FACTURACION;

#INDICAMOS AL SERVIDOR LA BASE DATOS A USAR
USE dbfacturacion;

#CREAR LA TABLA USUARIO
CREATE TABLE USUARIO
(CODIGO INT PRIMARY KEY,
ROL VARCHAR(50) NOT NULL,
CLAVE VARCHAR(50),
USUARIO VARCHAR(50),
EMAIL VARCHAR(320));

SELECT * FROM USUARIO;
SELECT * FROM EMPLEADO;

#CREAR TABLA EMPLEADO
CREATE TABLE EMPLEADO
(NOCEDULA BIGINT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(7),
CELULAR VARCHAR(10),
FECHANACIMIENTO VARCHAR(10), 
GENERO VARCHAR(30),
TIPODOC VARCHAR(50),
DIRECCION VARCHAR(100));

ALTER TABLE USUARIO
ADD USERID INT;

ALTER TABLE USUARIO
ADD FOREIGN KEY(USERID)
REFERENCES ROL(ID);

#AÑADIMOS UN CAMPOS ALA TABLA EMPLEADOS
ALTER TABLE EMPLEADO
ADD APELLIDO VARCHAR(50);





