#CREAR BASE DE DATOS
CREATE DATABASE facturacion

USE facturacion;



#CREAR TABLA TBLUSURIO
CREATE TABLE tblusuario
(codigo VARCHAR(10) PRIMARY KEY,
usuario VARCHAR(50) NOT NULL, 
rol VARCHAR(45) NOT NULL,
email VARCHAR(320) NOT NULL,
contraseña VARCHAR(20)  NOT NULL,
nombre VARCHAR(50) NOT NULL, 
apellido VARCHAR(50) NOT NULL);


#CREAR TABLA TBLCLIENTE
CREATE TABLE tblcliente(
codigo VARCHAR(10) PRIMARY KEY,
nombre VARCHAR(45) NOT NULL,
razon VARCHAR(50),
apellido VARCHAR(45) NOT NULL,
nocedula BIGINT NOT NULL,
tipodocumento VARCHAR(50) NOT NULL,
tipocliente VARCHAR(50) NOT NULL,
nit BIGINT,
email VARCHAR(320) NOT NULL,
telefono VARCHAR(7) NOT NULL,
celular VARCHAR(10),
direccion VARCHAR(100) NOT NULL,
municipio varchar(235) NOT NULL);


#CREAR TABLA TBLPRODUCTO
CREATE TABLE tblproducto
(codigo VARCHAR(10) PRIMARY KEY NOT NULL,
nombre VARCHAR(50) NOT NULL,
descripcion VARCHAR(100) NOT NULL,
categoria VARCHAR(50) NOT NULL,
estado VARCHAR(30) NOT NULL,
stock SMALLINT NOT NULL,
preciounitario FLOAT NOT NULL);

alter table tblproducto
add foto blob;

alter table tblproducto
add ruta varchar(50);

select * from tblproducto;


#CREAR TABLA TBLFACTURA
CREATE TABLE TBLFACTURA
(CODIGO VARCHAR(10) NOT NULL,
FECHA DATE NOT NULL,
CANTIDAD SMALLINT NOT NULL,
PRECIOVENTA FLOAT NOT NULL,
SUBTOTAL FLOAT NOT NULL,
TOTALPAGAR FLOAT NOT NULL,
IVA FLOAT  NOT NULL);

#CREAR TABLA TBLGENERADOR
CREATE TABLE TBLGENERADOR
(NOMBRETABLA VARCHAR(30) PRIMARY KEY NOT NULL,
NUMERO SMALLINT NOT NULL)



INSERT INTO TBLUSUARIO VALUES
('USU00000', 'admin', 'administrador', 'admin@correo.com', '123', 'juan', 'gonzales')
